name: Download and Upload to SFTP

on:
  push:
    branches:
      - main

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository (optional if code exists in repo)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 1: Download the file
      - name: Download File
        run: wget -O 1GB.bin https://ash-speed.hetzner.com/1GB.bin

      # Step 2: Upload to SFTP
      - name: Upload to SFTP
        env:
          SFTP_SERVER: eu-central-1.sftpcloud.io
          SFTP_USERNAME: 243edcb7adee4f75bf32ebd7f421efeb
          SFTP_PASSWORD: LljEeTr7UvRvKC26UWzLwMlAEoq2GgVi
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -e "
          open sftp://$SFTP_SERVER;
          user $SFTP_USERNAME $SFTP_PASSWORD;
          put 1GB.bin;
          bye;
          "
