name: pc-on

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Terminal Services 
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop in Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set User Password
      run: |
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $password

    - name: Create SSH Tunnel
      run: |
        New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.ssh
        wget "https://raw.githubusercontent.com/mollehya-boy666/Project1/refs/heads/main/mrabdellahshop.first.pem"
        Copy-Item -Path mrabdellahshop.first.pem -Destination $env:USERPROFILE\.ssh\id_rsa
        icacls $env:USERPROFILE\.ssh\id_rsa /inheritance:r
        icacls $env:USERPROFILE\.ssh\id_rsa /grant:r $env:USERNAME:`(R`)
        ssh-keyscan -H mrabdellahshop-36940.portmap.host >> $env:USERPROFILE\.ssh\known_hosts
        ssh -i $env:USERPROFILE\.ssh\id_rsa -o "StrictHostKeyChecking=no" \
            mrabdellahshop.first@mrabdellahshop-36940.portmap.host -N -R 36940:localhost:3389
