name: pc-on

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Terminal Services 
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop in Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set User Password
      run: |
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $password

    - name: Install ngrok using Chocolatey
      run: choco install ngrok -y

    - name: Add ngrok authtoken
      run: ngrok config add-authtoken 2qdUh48tuVBgtAAhA6FVWYeJZps_76VvqN3W3PWBUe1TP211V

    - name: Open TCP port 3389
      run: ngrok tcp 3389
