name: V2Ray Installation and Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-v2ray:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Update and Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y curl

    - name: Download and Install V2Ray
      run: |
        curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
        sudo bash install-release.sh

    - name: Verify Installation
      run: |
        sudo systemctl status v2ray || exit 1
        v2ray -version

    - name: Configure V2Ray
      run: |
        echo '{
          "log": {
            "loglevel": "warning"
          },
          "inbounds": [
            {
              "port": 1080,
              "protocol": "socks",
              "settings": {}
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {}
            }
          ]
        }' | sudo tee /usr/local/etc/v2ray/config.json

    - name: Start V2Ray Service
      run: |
        sudo systemctl restart v2ray
        sudo systemctl enable v2ray

    - name: Test V2Ray
      run: |
        curl -x socks5h://127.0.0.1:1080 http://www.google.com -m 10
